# Secrets are never passed to Lambda as plain env vars: functions get
# `<NAME>_SSM_PARAM=<path>` pointers and src/core/ssm.py resolves them (with
# decryption) at cold start.
locals {
  # Pre-existing, created by hand -- NOT managed here (read-only references).
  # Lambdas use the transaction pooler (6543), as Supabase recommends for
  # serverless; the session pooler (5432) is only used by CI for migrations.
  ssm_database_url         = "${var.ssm_prefix}/supabase/pooler-transaction-url"
  ssm_database_session_url = "${var.ssm_prefix}/supabase/session-pooler-url"

  # Optional vendor keys, NOT managed here either (so their values never land
  # in Terraform state). Create them once by hand:
  #   aws ssm put-parameter --type SecureString --name /finance-data-platform/app/fred-api-key --value <key>
  # Until they exist the functions just run without them (FRED needs its key,
  # OpenFIGI works anonymously at a lower rate limit).
  ssm_fred_api_key     = "${var.ssm_prefix}/app/fred-api-key"
  ssm_openfigi_api_key = "${var.ssm_prefix}/app/openfigi-api-key"

  ssm_api_key = aws_ssm_parameter.api_key.name
}

# Env master API key (X-API-Key admin; the API fails closed without it when
# ENV != local). Generated by Terraform so no manual bootstrap step is needed.
# NOTE: the generated value is stored in the Terraform state (private,
# encrypted state bucket). Read it with:
#   aws ssm get-parameter --with-decryption --name /finance-data-platform/app/api-key
resource "random_password" "api_key" {
  length  = 48
  special = false
}

resource "aws_ssm_parameter" "api_key" {
  name        = "${var.ssm_prefix}/app/api-key"
  description = "Master X-API-Key for the finance data platform API (admin scope)"
  type        = "SecureString"
  value       = random_password.api_key.result

  # Allow manual rotation (aws ssm put-parameter --overwrite) without
  # Terraform reverting it on the next apply.
  lifecycle {
    ignore_changes = [value]
  }
}
